@include('frontend.include.header')
    <div class="page-header section-start adver-header">
        <h1>Privacy Policy</h1>

    </div>
    <div class="container">
        <div class="content-page section-start">
            <div class="terms-page section-start">
                <p>This privacy policy applies to information collected by <strong>Two Degrees, Inc. </strong>(“Company”, “we” or “us”), on our Two Degrees mobile application or via our<strong> http://twodegrees.io </strong>website (collectively, the “App”).  This document will outline our privacy practices, including how we collect and utilize information obtained, as they pertain to visitors to and users of our App. It also describes the choices available to you regarding our use of your information and how you can opt-out of having your information collected.  By using or accessing the App, you consent to the terms of this privacy policy.  IF YOU DO NOT AGREE TO THIS PRIVACY POLICY YOU MAY NOT ACCESS OR OTHERWISE USE THE APP. </p>
                <p>&nbsp;</p>
                <p><strong>Information Collection</strong></p>
                
                <p>We may collect Personally Identifiable Information, such as your name, address, phone number, email address and other information from your address book, geolocation, and venues you choose to share with other users by "checking-in" via the App,  (collectively, “PII”), from the App when you choose to provide it to us.  For example, you may choose to send us PII about yourself in an email or by completing an online contact request form on the App.  We use this information to contact you to respond to your inquiry and as otherwise permitted by this privacy policy.   In addition, to take advantage of the best results of the App, you will need to agree to allow the App to perform certain geolocating functions.  Enabling this option means that you agree to provide certain information regarding your location to Company. When you choose to connect your social media account to the App, or otherwise access the App via a third party service, we collect PII from that social media platform and/or service, and you give us permission to access and use information, content, and/or material you have supplied to that service as permitted by that social media platform and/or service. For example, when you connect your Facebook, LinkedIn, Foursquare or Instagram account to register for the App, we may collect the personal information you have made publicly available in those accounts in your profile, such as your name, photograph, headline, contact information, experience, education, summary, location and other information. We may also obtain other non-public information from the social media account with your permission. You understand that you are responsible for the content, picture and check-ins posted as part of your profile information.  In addition, you understand that certain categories of information such as your user name, profile photo and venues you have checked-in to via the App are publicly available to other users and Company, and therefore will not be kept confidential. Our App may collect certain non-Personally Identifiable Information (“Non-PII”), such as your IP type, IP host address, ISP address, cookie IDs and segment IDs associated with cookie IDs, pages viewed and/or search terms entered, browser type, operating system, duration and frequency of visits, anonymous usage statistics including frequency of messaging and interaction with other users, clickstream data and other log file data.  On mobile devices, we may also collect device type, make and model, operating system, carrier, user ID, similar device IDs, and information about the apps you use.  Please note that we may use third party service providers to help operate and provide services in connection with our App and that these third party service providers will collect Non-PII from our App as well.  </p>
                <p>&nbsp;</p>
				<p><strong>Information Usage</strong></p>
                <p>We use the Non-PII we collect through our App for a variety of purposes, including to analyze interactions with and performance of our App.  We may also use Non-PII data from third parties (such as data vendors) pursuant to their own privacy policies, and provide access to or share Non-PII with any number of third parties, including but not limited to business partners, affiliates and advertising clients.  Similarly, we may enhance the Non-PII collected via our App with Non-PII collected from our business partners. </p>
                <p>We use your PII, as well as the PII in your address book contacts, and your social media contacts (including Facebook friends, LinkedIn contacts, Twitter followers, etc.).  We may use your PII, as provided by you through the App, to contact and correspond with you and/or to respond to your inquiries, as well as for other business purposes such as adding you to our marketing lists.  We do not sell your PII to third parties or mass marketers. We may disclose your information, including your PII, to third parties who are providing services on our behalf, as well as when we reasonably believe we are obligated to do so by law, and in order to investigate, prevent, or take action regarding suspected or actual prohibited activities, including but not limited to, fraud and situations involving potential threats to the safety of any person or property. In the event another company acquires all or most of our assets, all data compiled or owned by us may be among the items transferred in that transaction. In such event, all the data will continue to be governed by this privacy policy.  Finally, please note that if you specifically consent to additional uses of your PII, we may use your PII in a manner consistent with that consent.</p>
                 <p>&nbsp;</p>
				<p><strong>Cookies and Similar Technologies</strong></p>
                <p>"Cookies" are pieces of information that may be placed on your computer by a website for the purpose of facilitating and enhancing your communication and interaction with that website. Many websites use cookies for these purposes.  We and our business partners and advertisers may use cookies (or clear gifs, web beacons or similar devices, including devices that function in the mobile environment) to collect information from users for purposes such as tracking App and/or website visits.   We use both session ID cookies and persistent cookies. A session ID cookie expires when you close your browser.  A persistent cookie remains on your hard drive for up to two (2) years.   We set a persistent cookie to enable us to track the activity of users to enhance the services we provide.  You may stop or restrict the placement of cookies on your computer or remove them from your browser by adjusting your web browser preferences.  Note that this may cause some features of the App to work incorrectly.  Please note that cookie-based opt-outs are not effective on mobile applications.  However, on many mobile devices, application users may opt out of certain mobile tracking activities via their device settings. </p>
                <p>&nbsp;</p>
				<p><strong>Clickstream</strong></p>
                <p>As you use the Internet, a trail of electronic information is left at each website you visit. This information, which is sometimes referred to as "clickstream data," can be collected and stored by a website’s server. Clickstream data can tell us the type of computer and browsing software you use and the address of the website from which you linked to the App.  We may collect and use clickstream data to anonymously determine how much time visitors spend on each page of our App, how visitors navigate throughout the App and how we may tailor our web pages to better meet the needs of visitors.  This information will be used to improve our App and our services. Any collection or use of clickstream data will be anonymous, and will not intentionally contain any PII.</p>
                <p>&nbsp;</p>
				<p><strong>Security </strong></p>
                <p>We have undertaken and will undertake commercially reasonable efforts to prevent unauthorized Internet access to user data retained in our servers, however, due to the inherent open nature of the Internet, Company cannot ensure or warrant the security of any information provided online.  We retain Non-PII information collected via our App for up to five (5) years.  After that time, we aggregate the data and retain it for analytical purposes.  We retain your PII, if provided by you through the App, for as long as your inquiry is active (as determined by us) and for a reasonable time thereafter, or if applicable, for as long as you remain on our marketing list.  We also may retain your PII for a longer period of time as needed to provide you services or as necessary to comply with our legal obligations, to resolve disputes, and to enforce our agreements. Even if we delete some or all of your PII, we may continue to retain and use aggregate, anonymous data previously collected and/or anonymize and aggregate your personal information.  Please note that Company will not be liable for disclosures of your data due to errors or unauthorized acts of third parties.  </p>
                 <p>&nbsp;</p>
				 <p><strong>Third Party Apps and Social Media Platforms </strong></p>
				<p>Our App or advertisements we place may contain links to other websites or Apps. Other websites or Apps may also reference or link to our App.  Some of our third-party website or technology partners may place their own cookies and/or other data collection tools on your Internet browser; however, we have no access to or control over these cookies and/or other data collection tools. These other domains, websites and/or apps are not controlled by us.  We encourage our users to read the privacy policies of each and every website and app that they interact with.  We do not endorse, screen or approve, and are not responsible for the privacy practices or content of such other websites or apps.  Visiting these other websites or apps is at your own risk. </p>
				<p>Our App may also interface with social media platforms. You may be given the choice of connecting to one or more social media platforms from this App and sharing your check-ins via the App on your Facebook or Foursquare wall or account. If you choose to do so, then depending upon your social media privacy settings, the personal information that you post, transmit, or otherwise make available on the social media platform may be viewed and/or used by others and we will have no control over such viewing and use. We do not control and are not responsible for any use of your PII by or through any of the social media platforms. By linking to any social media platform, you will be assuming the risk that the PII you provide on that platform may be viewed and/or used by third parties for any purposes and agree that we have no control or responsibility for such third party viewing and uses.</p>
				<p>&nbsp;</p>
				<p><strong>Information Relating to Children </strong></p>
				<p>Our App is designed for those 13 years of age and older. We do not knowingly collect information from anyone under the age of 13. If we are made aware that we have received such information, or any information in violation of our policy, we will use reasonable efforts to locate and remove that information from our records.</p>
				<p>&nbsp;</p>
				<p><strong>Policy Modifications:</strong></p>
				<p>We reserve the right, at our discretion, to modify, add, or remove portions from this policy at any time.  However, if at any time in the future we plan to use any data in a way that materially differs from this policy, we will post such changes here.  We encourage you to periodically review the App for the latest information on our privacy practices.</p>
				<p>&nbsp;</p>
				<p><strong>App Terms of Use</strong></p>
				<p>Use of this App is governed by, and subject to, the legal notices contained at the Terms of Use available at http://twodegrees.io. Your use, or access, of the App constitutes your agreement to be bound by these provisions.<strong> IF YOU DO NOT AGREE TO THESE TERMS OF USE YOU MAY NOT ACCESS OR OTHERWISE USE THE APP.</strong></p>
				<p>&nbsp;</p>
				<p><strong>Opt-Out</strong></p>
				<p>By providing your email address and mobile number to us, you expressly consent to receive email, SMS and MMS text message from us.  We may contact you by email, telephone, text messages or otherwise to verify your account, and for informational, application functionality and operational purposes (provided that we will not give your email address or mobile number to another party to promote their products or services directly to you).  If you receive an email from us, you may unsubscribe from future unsolicited emails through a link, typically at the bottom of the e-mail.  To stop receiving mobile messages, text STOP to the provided short code. For help, text HELP to the provided short code, call 518.712.9466 or email optout@twodegrees.io . Texting CANCEL, END, QUIT, or UNSUBSCRIBE will also prevent further message interaction with the App.</p>
				<p>If you have consented to have your PII shared with any third party who may use such information for direct marketing purposes and you no longer wish to have your PII shared with such parties, then you may opt-out of such disclosures by sending an email to optout@twodegrees.io. However, we are not responsible for removing your PII from the lists of any third party who has previously been provided with your information in accordance with this privacy policy or your separate consent.</p>
				<p>&nbsp;</p>
				<p><strong>Comments and Questions</strong></p>
				<p>We use reasonable processes to ensure compliance with this privacy policy and periodically verify that the policy is accurate.  We encourage you to raise any concerns using the contact information provided below, and we will investigate and attempt to resolve any complaints and disputes regarding use and disclosure of information.  You may also request access to your PII (if you have provided PII to us through the App) and information about our collection, use, and disclosure of that information by using the contact information provided below.  Subject to certain exceptions prescribed by law, you will be given reasonable access to your personal information, entitlement to challenge the accuracy and completeness of the information, and the ability to have it amended as is appropriate.  You can help us maintain the accuracy of your information by notifying us of any changes to your personal information. </p>
				<p>&nbsp;</p>
				<p>Via Email: support@twodegrees.io</p>
				<p>&nbsp;</p>
				<p>Via Regular Mail</p>
				<p>103 Eisenhower Parkway</p>
				<p>Box 610</p>
				<p>Roseland, NJ07068</p>
				<p>&nbsp;</p>
				<p><strong>United States of America</strong></p>
				<p>Our App is maintained in the United States of America.  By using the App, you authorize the export of your information to the USA and its storage and use as specified in this policy.</p>
				<p>&nbsp;</p>
				<p><strong>Effective Date: </strong> This privacy policy is effective and was last updated on April 10, 2015. </p>
			
			</div>
        </div>
    </div>
@include('frontend.include.footer')
    <script src="{{ asset('public/frontend/js/jquery.min.js') }}"></script>
    <script src="{{ asset('public/frontend/js/bootstrap.js') }}"></script>
</body>
