@include('frontend.include.header')
    <div class="page-header section-start adver-header">
        <h1>Terms and Conditions</h1>

    </div>
    <div class="container">
        <div class="content-page section-start">
            <div class="terms-page section-start">
                <p>Welcome to the twodegrees mobile application and www.twodegrees.io website (collectively, the “App”). This App is maintained and operated by <strong>Two Degrees, Inc.</strong> (“Company”). </p>
                <p>&nbsp;</p>
                <p><strong>Your access and use of the App is subject to the following terms and conditions (the "terms and conditions") and all applicable laws.  By accessing or using any part of the App, you accept, without limitation or qualification, these terms and conditions.  If you do not agree with all of the terms and conditions set forth below, you may not use any portion of the App.</strong></p>
                <p>&nbsp;</p>
                <p><strong>Authorized Use of App:</strong>&nbsp;&nbsp;This App is provided for your personal and non-commercial use and for informational purposes only. Any other use of the App requires the prior written consent of Company.</p>
                <p>&nbsp;</p>
                <p><strong>Unauthorized Use of App:</strong>&nbsp;&nbsp;You may not use spiders, robots, data mining techniques or other automated devices or programs to catalog, download or otherwise reproduce, store or distribute content available on the App. Further, you may not use any such automated means to manipulate the App, such as automating what are otherwise manual or one-off procedures. You may not take any action to interfere with, or disrupt, the App or any other user's use of the App, including, without limitation, via means of overloading, “flooding”, or “crashing” the App, circumventing security or user authentication measures or attempting to exceed the limited authorization and access granted to you under these Terms and Conditions. You may not frame portions of the App within another website or application.  You may not resell use of, or access to, the App to any third party without our prior written consent. </p>
                <p>&nbsp;</p>
                <p><strong>Registration and Passwords:</strong>&nbsp;&nbsp; In order to access certain services on the App, you may be required to provide specific information. All information about you must be truthful, and you may not use any aliases or other means to mask your true identity. Any access codes or passwords provided should be safeguarded at all times. You are responsible for the security of your access codes and passwords and will be solely liable for any use or unauthorized use under such access codes or passwords. We may suspend or terminate your access at any time with or without notice. To understand how we use information collected from you, including information collected via social media connectivity, please read our Privacy Policy, www.twodegrees.io/privacy. </p>
                <p>&nbsp;</p>
                <p><strong>Proprietary Rights:</strong>&nbsp;&nbsp;Company is the owner of or otherwise licensed to use all parts of the App, including all copy, software, graphics, designs and all copyrights, trademarks, service marks, trade names, logos, and other intellectual property or proprietary rights contained therein. Some materials on the App belong to third parties who have authorized Company to display the materials, such as portfolio works, client logos and trademarks and other proprietary materials.  By using the Service, you agree not to copy, distribute, modify or make derivative works of any materials without the prior written consent of the owner of such materials.  <strong>Except as expressly set forth in these Terms and Conditions, no license is granted to you and no rights are conveyed by virtue of accessing or using the App.  All rights not granted under these Terms and Conditions are reserved by Company.</strong></p>
                <p>&nbsp;</p>
                <p><strong>Comments or Materials Posted by You: </strong>&nbsp;&nbsp;Certain pages on the App may allow you to post text comments, photos, videos, check-ins at venues or other Content (“Content”).  Unless otherwise specified, you may only post Content to the App if you are a resident of the United States and are thirteen (13) years of age or older.  You may only post Content that you created or which the owner of the Content has given you permission to post.  If Content depicts any person other than yourself, you must have permission from that person or, if that person is a minor, permission from that person’s parent or legal guardian, before you post the Content. You may be required to provide proof of such permission to Company.  You may not post or distribute Content that is illegal or that violates these Terms and Conditions.  You represent and warrant that (a) you own all the rights to the Content or are authorized to use and distribute the Content to the App and (b) the Content does not and will not infringe any copyright, right of publicity, or any other third-party right nor violate any law or regulation.</p>
                <p>By submitting or posting Content to the App, you grant Company the irrevocable, perpetual, worldwide right to reproduce, display, perform, distribute, adapt, and promote this Content in any medium.  Once you submit or post Content to the App, Company does not need to give you any further right to inspect or approve uses of such Content or to compensate you for any such uses.  Company owns all rights, title, and interest in any compilation, collective work, or other derivative work created by Company using or incorporating Content posted to the Apps. You are solely responsible for anything you may post on the App and the consequences of posting anything on the App.</p>
                 <p><strong>Content Posted by Other Users</strong> </p>
                <p><strong>Activities Prohibited by App: </strong>&nbsp;&nbsp; Company expects all of its users to be respectful of other people.  The following is a partial list of the types of conduct that are illegal or prohibited on the App or while using the App. Company reserves the right to investigate and take appropriate legal action against anyone who, in Company’s sole discretion, engages in any of the prohibited activities.  Without limitation, you agree that you will not post or transmit to other users anything that contains Content that:</p>
                <ul class="terms-list">
                <li>is defamatory, abusive, obscene, profane or offensive;</li>
                <li>infringes or violates another party's intellectual property rights (such as music, videos, photos or other materials for which you do not have written authority from the owner of such materials to post on the App);</li>
                <li>violates any party’s right of publicity or right of privacy;</li>
                <li>is threatening, harassing or that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual;</li>
                    <li>promotes or encourages violence;</li>
                    <li>is inaccurate, false or misleading in any way;</li>
                    <li>is illegal or promotes any illegal activities;</li>
                    <li>promotes illegal or unauthorized copying of another person's copyrighted work or links to them or providing information to circumvent security measures;</li>
                    <li>contains “masked” profanity (i.e., F*@&#);</li>
                    <li>contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; or</li>
                    <li>contains any advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation.</li>
                    
                </ul>
                <p>Company is under no obligation to screen or monitor Content, but may review Content from time to time at its sole discretion.  Company will make all determinations as to what Content is appropriate in its sole discretion.  Company may edit or remove any Content at any time without notice.</p>
                <p><strong>No Ideas Accepted: </strong>&nbsp;Company does not accept any unsolicited ideas from outside the Company including without limitation suggestions about advertising, promotion or merchandising of our products, additions to our product lines, services, or changes in methods of doing business.  We may already be working on or may in the future work on a similar idea. This policy eliminates concerns about ownership of such ideas. If, notwithstanding this policy, you submit an unsolicited idea to this App, you understand and acknowledge that such idea is not submitted in confidence and Company assumes no obligation, expressed or implied, by considering it. You further understand that Company shall exclusively own all known or hereafter existing rights to the idea everywhere in the world, and that such idea is hereby irrevocably assigned to Company.  Without limiting the foregoing, to the extent any such assignment is deemed unenforceable, you hereby grant Company an irrevocable, perpetual, world-wide license to use the idea in any manner, in any medium now known or hereafter developed, without compensation to you. </p>
                <p>&nbsp;</p>
                <p><strong>Links:</strong>&nbsp;&nbsp; This App may contain links to other websites or applications not maintained by Company. Other websites or apps may also reference or link to our App. We encourage you to be aware when you leave our App and to read the terms and conditions and privacy statements of each and every website or app that you visit.  We are not responsible for the practices or the content of such other websites or apps.</p>
                <p>&nbsp;</p>
                <p><strong>No Warranties:</strong>&nbsp;&nbsp; WHILE COMPANY USES REASONABLE EFFORTS TO INCLUDE UP-TO-DATE INFORMATION ON THE APP, COMPANY MAKES NO WARRANTIES OR REPRESENTATIONS AS TO ITS ACCURACY OR COMPLETENESS. COMPANY ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY ERRORS OR OMISSIONS IN THE CONTENT ON THE APP. YOUR USE OF THE APP IS AT YOUR OWN RISK. THE APP, INCLUDING ALL CONTENT MADE AVAILABLE ON OR ACCESSED THROUGH THE APP, IS PROVIDED "AS IS" AND COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER FOR THE CONTENT ON THE APP. FURTHER, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, COMPANY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, NON-INFRINGEMENT, TITLE, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. COMPANY DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE APP OR ANY MATERIALS OR CONTENT CONTAINED THEREIN WILL BE UNINTERRUPTED OR ERROR FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE APP OR THE SERVER THAT MAKES IT AVAILABLE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. COMPANY SHALL NOT BE LIABLE FOR THE USE OF THE APP, INCLUDING, WITHOUT LIMITATION, THE CONTENT AND ANY ERRORS CONTAINED THEREIN. IN NO EVENT WILL COMPANY BE LIABLE UNDER ANY THEORY OF TORT, CONTRACT, STRICT LIABILITY OR OTHER LEGAL OR EQUITABLE THEORY FOR ANY LOST PROFITS, LOST DATA, LOST OPPORTUNITIES, COSTS OF COVER, EXEMPLARY, PUNITIVE, PERSONAL INJURY/WRONGFUL DEATH, SPECIAL, INCIDENTAL, INDIRECT OR OTHER CONSEQUENTIAL DAMAGES, OR FOR ANY DIRECT DAMAGES, EACH OF WHICH IS HEREBY EXCLUDED BY AGREEMENT OF THE PARTIES REGARDLESS OF WHETHER OR NOT EITHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                <p>&nbsp;</p>
                <p>YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER USERS OF THE APP. YOU UNDERSTAND THAT THE COMPANY CURRENTLY DOES NOT CONDUCT CRIMINAL BACKGROUND CHECKS OR SCREENINGS OF THESE OTHER USERS. THE COMPANY ALSO DOES NOT INQUIRE INTO THE BACKGROUNDS OF ITS USERS. THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF ITS USERS OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE USERS FOR ANY PURPOSE.</p>
                <p>&nbsp;</p>
                <p>If any part of these warranty disclaimers or limitations of liability is found to be invalid or unenforceable for any reason or if we are otherwise found to be liable to you in any manner, then our aggregate liability for all claims under such circumstances for liabilities, shall not exceed the amount paid by you, if any, for accessing this App. </p>
                <p>&nbsp;</p>
                <p><strong>Indemnification:</strong>&nbsp;&nbsp;You agree to indemnify, defend and hold harmless Company, its employees, directors, officers, agents, business partners, affiliates, contractors, distribution partners and representatives from and against any and all claims, demands, liabilities, costs or expenses, including attorney’s fees and costs, arising from, or related to, any breach by you of any of these Terms and Conditions or applicable law. </p>
                <p>&nbsp;</p>
                <p><strong>Severability.</strong>&nbsp;&nbsp;If any part of these Terms and Conditions shall be held or declared to be invalid or unenforceable for any reason by any court of competent jurisdiction, such provision shall be ineffective but shall not affect any other part of these Terms and Conditions, and in such event, such provision shall be changed and interpreted so as to best accomplish the objectives of such unenforceable or invalid provision within the limits of applicable law or applicable court decisions.</p>
                <p>&nbsp;</p>
                <p><strong>Waiver; Remedies:</strong>&nbsp;&nbsp;The failure of Company to partially or fully exercise any rights or the waiver of Company of any breach of these Terms and Conditions by you shall not prevent a subsequent exercise of such right by Company or be deemed a waiver by Company of any subsequent breach by you of the same or any other term of these Terms and Conditions.  The rights and remedies of Company under these Terms and Conditions and any other applicable agreement between you and Company shall be cumulative, and the exercise of any such right or remedy shall not limit Company's right to exercise any other right or remedy.</p>
                <p>&nbsp;</p>
                <p><strong>Digital Millennium Copyright Act ("DMCA") Notice: [WE CAN DISCUSS DMCA REGISTRATION IF NECESSARY I.E. IF USERS CAN UPLOAD CONTENT.  IF THAT IS NOT THE CASE, WHICH IT APPEARS NOT TO BE, WE CAN REMOVE THIS]</strong></p>
                <p>Materials may be made available via the App by third parties not within our control. We are under no obligation to, and do not, scan content posted on the App for the inclusion of illegal or impermissible content. However, we respect the copyright interests of others. It is our policy not to permit materials known by us to infringe another party’s copyright to remain on the App.</p>
                
                <p>&nbsp;</p>
                <p>If you believe any materials on the App infringe a copyright, you should provide us with written notice that at a minimum contains:</p>
                <p>&nbsp;</p>
                <p class="terms-points">(i) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
                <p class="terms-points">(ii) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online website are covered by a single notification, a representative list of such works at that website;</p>
                <p class="terms-points">(iii) &nbsp;&nbsp;&nbsp;&nbsp; Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;</p>
                <p class="terms-points">(iv) &nbsp;&nbsp;&nbsp;&nbsp; Information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted;</p>
                <p class="terms-points">(v) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
                <p class="terms-points">(vi) &nbsp;&nbsp;&nbsp;&nbsp; A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
                <p>&nbsp;</p>
                <p>All DMCA notices should be sent to our designated agent as follows:</p>
                <p>&nbsp;</p>
                <p>Contact: Two Degrees Support</p>
                <p>Contact email address: support@twodegrees.io</p>
                <p>&nbsp;</p>
                <p>It is our policy to terminate relationships regarding content with third parties who repeatedly infringe the copyrights of others. </p>
                <p>&nbsp;</p>
                <p><strong>International Access:</strong>&nbsp;&nbsp;Our App is provided from the United States of America and all servers that make it available reside in the U.S.A.  The laws of other countries may differ regarding the access and use of the App.  We make no representations regarding the legality of this App in any other country and it is your responsibility to ensure that your use complies with all applicable laws outside of the U.S.A. </p>
                <p>&nbsp;</p>
                <p><strong>Additional Terms for Users of Apple Devices</strong></p>
                <p>If you have downloaded the App via the iTunes Store, the following shall apply: You acknowledge and agree that these Terms and Conditions are solely between you and us, not Apple, and that Apple has no responsibility for the Services. Your use of the Services must comply with Apple’s App Store Terms and Conditions, located at http://www.apple.com/legal/internet-services/itunes/us/terms.html. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the Services. In the event of any failure of the App to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price, if any, for the App to you. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be solely governed by these Terms and Conditions and any law applicable to us as provider of the software. You acknowledge that Apple is not responsible for addressing any claims by you or any third party relating to the App or your possession and/or use of the App including, but not limited to: (i) product liability claims; (ii) any claim that the iTunes-Sourced Software fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation; and all such claims are governed solely by these Terms and Conditions and any law applicable to us as provider of the App. You acknowledge that, in the event of any third party claim that the App or your possession and use of the App infringes that third party’s intellectual property rights, we, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms and Conditions. You and we acknowledge and agree that Apple, and Apple’s subsidiaries, are third party beneficiaries of these Terms and Conditions as relates to your license of the App, and that, upon your acceptance of these terms and conditions of these Terms and Conditions, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms and Conditions as relates to your license of the App against you as a third party beneficiary thereof.  You represent that you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
                <p>&nbsp;</p>
                <p><strong>Governing Law. </strong>&nbsp;&nbsp;The laws of the State of New York shall govern these Terms and Conditions.  YOU HEREBY WAIVE ALL RIGHTS TO TRIAL IN ANY ACTION OR PROCEEDING INSTITUTED IN CONNECTION WITH THE APP OR THESE TERMS OF USE. ANY CONTROVERSY OR CLAIM ARISING OUT OF OR RELATING TO THE APP OR THESE TERMS OF USE SHALL BE SETTLED BY BINDING ARBITRATION IN ACCORDANCE WITH THE COMMERCIAL ARBITRATION RULES OF THE AMERICAN ARBITRATION ASSOCIATION. ANY SUCH CONTROVERSY OR CLAIM SHALL BE ARBITRATED ON AN INDIVIDUAL BASIS, AND SHALL NOT BE CONSOLIDATED IN ANY ARBITRATION WITH ANY CLAIM OR CONTROVERSY OF ANY OTHER PARTY. THE ARBITRATION SHALL BE CONDUCTED IN NEW YORK.</p>
                <p>FOR ANY MATTERS WHICH ARE NOT SUBJECT TO ARBITRATION AS SET FORTH IN THESE TERMS OF USE AND/OR IN CONNECTION WITH THE ENTERING OF ANY JUDGMENT ON AN ARBITRATION AWARD IN CONNECTION WITH THESE TERMS OF USE, YOU HEREBY EXPRESSLY CONSENT TO EXCLUSIVE JURISDICTION AND VENUE IN THE COURTS LOCATED IN NEW YORK.</p>
                <p>ANY CLAIMS ASSERTED BY YOU IN CONNECTION WITH THE APP MUST BE ASSERTED IN WRITING TO US WITHIN ONE (1) YEAR OF THE DATE SUCH CLAIM FIRST AROSE, OR SUCH CLAIM IS FOREVER WAIVED BY YOU.  EACH CLAIM SHALL BE ADJUDICATED INDIVIDUALLY, AND YOU AGREE NOT TO COMBINE YOUR CLAIM WITH THE CLAIM OF ANY THIRD PARTY.</p>
                <p>&nbsp;</p>
                <p><strong>Questions:</strong>&nbsp;&nbsp;Should you have any questions regarding these Terms and Conditions you may contact us at webmaster@twodegrees.io.</p>
                <p>&nbsp;</p>
                <p>These Terms and Conditions are effective and were last updated on January 25, 2016.</p>
            </div>
        </div>
    </div>
@include('frontend.include.footer')
    <script src="{{ asset('public/frontend/js/jquery.min.js') }}"></script>
    <script src="{{ asset('public/frontend/js/bootstrap.js') }}"></script>
</body>
